import type { TimelineData } from '@fg/shared';

/** The career timeline — real roles, employers and technologies from 2000 to today,
 *  grouped into era time-blocks, with side projects placed chronologically. Ported from
 *  the design prototype; tech names key into the shared TECH_REGISTRY for icons/colors. */

/** Era labels, defined once. Entries are grouped by an exact string match on `era`, so a
 *  single source of truth here prevents a stray character from silently splitting a block.
 *  The values double as the rendered era headings. */
const ERAS = {
	now: '2026 — Now',
	netherlands2020s: '2020s — Netherlands (remote from Spain)',
	netherlandsLate2010s: 'Late 2010s — Netherlands',
	melbourne: '2013–2017 — Melbourne, Australia',
	brisbane: '2007–2013 — Brisbane, Australia',
	earlyWeb: '2000–2006 — The Early Web (Netherlands & New Zealand)',
} as const;

const timeline: TimelineData = {
	entries: [
		{
			id: 'portfolio',
			era: ERAS.now,
			years: '2026',
			startYear: 2026,
			endYear: 'present',
			client: 'Portfolio Site',
			role: 'Full-Stack Engineer',
			type: 'independent',
			highlight: '3 frameworks, 1 site — you’re looking at it',
			tech: {
				frontend: ['React', 'Angular', 'Vue', 'Vite', 'CSS Modules'],
				backend: ['Bun', 'Hono'],
				cicd: ['GitHub Actions', 'Docker'],
				ai: ['Claude Code'],
			},
		},
		{
			id: 'ai-healthcare',
			era: ERAS.now,
			years: '2026',
			startYear: 2026,
			endYear: 2026,
			client: 'AI Healthcare Startup',
			role: 'Consulting Engineer',
			type: 'independent',
			tech: {
				frontend: ['React', 'SCSS Modules'],
				backend: ['Java', 'Spring Boot'],
				cicd: ['Docker'],
				ai: ['Claude Code', 'Ollama'],
			},
		},
		{
			id: 'market-breadth',
			era: ERAS.now,
			years: '2025–26',
			startYear: 2025,
			endYear: 2026,
			client: 'Market Breadth Dashboard',
			role: 'Full-Stack Engineer',
			type: 'independent',
			highlight: 'Real-time WebSocket market-data ingestion',
			tech: {
				frontend: ['React', 'Mantine UI', 'Vite', 'Recharts', 'CSS Modules'],
				backend: ['NestJS', 'TimescaleDB', 'WebSockets'],
				cicd: ['Gitea Actions', 'Docker', 'Nx'],
				ai: ['Claude Code', 'MCP'],
			},
		},
		{
			id: 'py-market-structure',
			era: ERAS.now,
			years: '2025–26',
			startYear: 2025,
			endYear: 2026,
			client: 'py-market-structure',
			role: 'PyPI library',
			type: 'side-project',
			highlight: 'Published to PyPI with almost zero prior Python — built with Claude Code',
			tech: {
				frontend: ['Angular', 'RxJS', 'lightweight-charts', 'SCSS Modules'],
				backend: ['Python', 'PyPI'],
				cicd: ['GitHub Actions'],
				ai: ['Claude Code', 'MCP'],
			},
		},
		{
			id: 'amsterdam',
			era: ERAS.netherlands2020s,
			years: '2020–25',
			startYear: 2020,
			endYear: 2025,
			client: 'Gemeente Amsterdam',
			role: 'Lead Full-Stack Engineer — 5.5 years',
			type: 'independent',
			highlight: 'Led frontend across multiple teams; monorepo + feature-sliced architecture',
			tech: {
				frontend: [
					'React',
					'Redux',
					'TypeScript',
					'GraphQL',
					'Storybook',
					'Webpack',
					'SWC',
					'Styled Components',
					'CSS Modules',
				],
				backend: [
					'Node.js',
					'Express',
					'NestJS',
					'Symfony',
					'RxJS',
					'Azure',
					'PostgreSQL',
					'PostGIS',
					'Blob Storage',
					'Azure Service Bus',
				],
				cicd: [
					'Nx',
					'GitLab CI',
					'Azure Pipelines',
					'GitHub Actions',
					'Docker',
					'AKS',
					'App Insights',
				],
				ai: ['Copilot', 'ChatGPT', 'ChatGPT API'],
			},
		},
		{
			id: 'neurofeedback-ijburg',
			era: ERAS.netherlands2020s,
			years: '2021',
			startYear: 2021,
			endYear: 2021,
			client: 'Neurofeedback IJburg',
			role: 'Freelance Web Developer',
			type: 'independent',
			highlight:
				'Multilingual static site for a private practice — Nuxt SSG, i18n, interactive maps',
			tech: {
				frontend: ['Vue', 'Nuxt', 'SCSS', 'Leaflet'],
			},
		},
		{
			id: 'trading-system',
			era: ERAS.netherlands2020s,
			years: '2018–now',
			startYear: 2018,
			endYear: 'present',
			client: 'Crypto Trading System',
			role: 'Parallel to employment',
			type: 'side-project',
			highlight: 'Autonomous execution, exchange APIs, homelab infra',
			tech: {
				frontend: [
					'React',
					'Zustand',
					'Next.js',
					'Anychart',
					'RxJS',
					'Webpack',
					'SWC',
					'SCSS Modules',
				],
				backend: ['Node.js', 'Express', 'NestJS', 'PostgreSQL'],
				cicd: ['Nx', 'Bitbucket', 'Jenkins', 'Gitea Actions', 'Docker', 'Pulumi', 'k3s'],
				ai: ['ChatGPT API', 'Claude Code', 'MCP', 'OpenClaw'],
			},
		},
		{
			id: 'tele2',
			era: ERAS.netherlandsLate2010s,
			years: '2017–19',
			startYear: 2017,
			endYear: 2019,
			client: 'Tele2',
			role: 'Lead Full-Stack Engineer',
			type: 'employee',
			highlight: [
				'E-commerce SSR rebuild — 3× Lighthouse improvement',
				'Beat both the previously-optimized Magento 2 site and the AMP build Google’s own consultants delivered',
			],
			tech: {
				frontend: ['React', 'Redux', 'TypeScript/Flow', 'SSR', 'Webpack', 'SCSS Modules'],
				backend: ['Node.js', 'Express', 'PHP', 'Salesforce', 'MySQL'],
				cicd: ['Jenkins', 'Docker'],
			},
		},
		{
			id: 'deloitte-nl',
			era: ERAS.netherlandsLate2010s,
			years: '2017',
			startYear: 2017,
			endYear: 2017,
			client: 'Deloitte Digital NL',
			role: 'Senior Frontend Engineer',
			type: 'employee',
			highlight: 'Bridged Melbourne & Amsterdam frontend teams',
			tech: {
				frontend: ['React', 'Redux', 'ES2016', 'SCSS', 'Webpack'],
				backend: ['AEM'],
			},
		},
		{
			id: 'deloitte-au-manager',
			era: ERAS.melbourne,
			years: '2016–17',
			startYear: 2016,
			endYear: 2017,
			client: 'Deloitte Digital AU',
			role: 'Frontend Lead (Manager)',
			type: 'employee',
			highlight: [
				'Built CI/CD pipelines adopted across the practice, and a form framework reused across projects',
				'A hands-on manager — at least half my time stayed in the code',
			],
			tech: {
				frontend: ['React', 'ES2016', 'Webpack', 'SCSS', 'Webpack', 'JSPM'],
				backend: ['Sitecore', 'SQL Server'],
				cicd: ['Bamboo'],
			},
		},
		{
			id: 'dastoon',
			era: ERAS.melbourne,
			years: '2016',
			startYear: 2016,
			endYear: 2016,
			client: 'Dastoon',
			role: 'Technical direction & QA',
			type: 'independent',
			highlight: 'Technical direction and QA over an outsourced Magento 2 fashion store',
			tech: {
				frontend: ['jQuery', 'HTML5', 'CSS3'],
				backend: ['PHP', 'Magento 2', 'MySQL'],
			},
		},
		{
			id: 'deloitte-au-consultant',
			era: ERAS.melbourne,
			years: '2013–16',
			startYear: 2013,
			endYear: 2016,
			client: 'Deloitte Digital AU',
			role: 'Frontend Engineer (Senior Consultant)',
			type: 'employee',
			highlight: 'Brought parallel Gulp builds to the frontend guild',
			tech: {
				frontend: ['AngularJS', 'Backbone', 'jQuery', 'Highcharts', 'SCSS', 'Webpack'],
				backend: ['Sitecore', 'SQL Server'],
				cicd: ['Bamboo', 'Grunt', 'Gulp', 'Yeoman', 'Middleman'],
			},
		},
		{
			id: 'isobar',
			era: ERAS.melbourne,
			years: '2013',
			startYear: 2013,
			endYear: 2013,
			client: 'Visual Jazz Isobar',
			role: 'Senior Frontend Engineer',
			type: 'independent',
			highlight: 'First taste of build automation — Grunt for the front-end pipeline',
			tech: {
				frontend: ['AngularJS', 'RequireJS', 'Webpack'],
				backend: ['PHP', 'AEM', 'MySQL', 'Wordpress'],
				cicd: ['Grunt'],
			},
		},
		{
			id: 'limelight',
			era: ERAS.brisbane,
			years: '2012–13',
			startYear: 2012,
			endYear: 2013,
			client: 'Limelight Digital',
			role: 'Senior Full-Stack Developer',
			type: 'employee',
			highlight:
				'They didn’t want to lose me — kept on remotely through a Brisbane to Melbourne move',
			tech: {
				frontend: ['jQuery', 'Backbone', 'Marionette', 'HTML5', 'CSS3'],
				backend: ['PHP', 'MySQL', 'Kohana', 'Node.js', 'Wordpress'],
			},
		},
		{
			id: 'cru-digital',
			era: ERAS.brisbane,
			years: '2010–12',
			startYear: 2010,
			endYear: 2012,
			client: 'Cru Digital',
			role: 'Senior Full-Stack Developer',
			type: 'employee',
			highlight: [
				'First single-page apps — hand-rolled in jQuery, a plugin per view — as responsive design took hold',
				'Early cloud — building CentOS AMI images from scratch on EC2',
			],
			tech: {
				frontend: ['jQuery', 'Ext JS', 'HTML5', 'CSS3'],
				backend: ['PHP', 'MySQL', 'SnappCMS', 'Magento'],
				cicd: ['Mercurial', 'Amazon EC2'],
			},
		},
		{
			id: 'mmplugins',
			era: ERAS.brisbane,
			years: '2008–12',
			startYear: 2008,
			endYear: 2012,
			client: 'mmPlugins',
			role: 'Joomla extensions',
			type: 'side-project',
			highlight:
				'Free and commercial Joomla extensions, built full-stack — a three-person venture',
			tech: {
				frontend: ['jQuery', 'JavaScript', 'HTML5', 'CSS3'],
				backend: ['PHP', 'MySQL', 'Joomla', 'Joomla 2'],
				cicd: ['Bash', 'SFTP'],
			},
		},
		{
			id: 'ifactory',
			era: ERAS.brisbane,
			years: '2007–10',
			startYear: 2007,
			endYear: 2010,
			client: 'iFactory',
			role: 'Lead Full-Stack Engineer',
			type: 'employee',
			highlight: 'Lived through the Prototype.js → MooTools → jQuery era',
			tech: {
				frontend: ['Prototype.js', 'MooTools', 'jQuery', 'HTML5', 'CSS3'],
				backend: ['PHP', 'MySQL', 'Joomla', 'Joomla 2', 'Magento', 'Seagull', 'PEAR'],
				cicd: ['SVN', 'rsync', 'Capistrano'],
			},
		},
		{
			id: 'cms-v2',
			era: ERAS.brisbane,
			years: '2008',
			startYear: 2008,
			endYear: 2009,
			client: 'Custom CMS v2',
			role: 'Seagull Framework',
			type: 'side-project',
			highlight: 'Built another CMS from scratch — this time on the Seagull PHP framework',
			tech: {
				frontend: ['jQuery', 'JavaScript', 'CSS3'],
				backend: ['PHP', 'MySQL'],
				cicd: ['Capistrano'],
			},
		},
		{
			id: 'hids',
			era: ERAS.earlyWeb,
			years: '2005–06',
			startYear: 2005,
			endYear: 2006,
			client: 'HIDS',
			role: 'Web Developer',
			type: 'employee',
			highlight: [
				'XMLHttpRequest was the new hotness',
				'Kept on remotely through a move from the Netherlands to New Zealand',
			],
			tech: {
				frontend: ['JavaScript', 'AJAX'],
				backend: ['PHP', 'MySQL', 'In-house CMS'],
				cicd: ['SFTP'],
			},
		},
		{
			id: 'cms-v1',
			era: ERAS.earlyWeb,
			years: '2003–05',
			startYear: 2003,
			endYear: 2005,
			client: 'Custom CMS v1',
			role: 'Built from scratch',
			type: 'side-project',
			highlight: 'Full CMS built from scratch in PHP',
			tech: {
				frontend: ['JavaScript', 'XHTML', 'CSS2'],
				backend: ['PHP', 'MySQL'],
				cicd: ['SFTP'],
			},
		},
		{
			id: 'freelance-early',
			era: ERAS.earlyWeb,
			years: '2003–04',
			startYear: 2003,
			endYear: 2004,
			client: 'Freelance',
			role: 'Web Developer',
			type: 'independent',
			tech: {
				frontend: ['JavaScript', 'XHTML', 'CSS2'],
				backend: ['PHP'],
				cicd: ['SFTP'],
			},
		},
		{
			id: 'edf',
			era: ERAS.earlyWeb,
			years: '2002–03',
			startYear: 2002,
			endYear: 2003,
			client: 'EDF',
			role: 'Web Developer',
			type: 'employee',
			tech: {
				frontend: ['JavaScript', 'XML', 'XSLT'],
				backend: ['ASP.NET', 'PHP', 'SQL Server', 'In-house CMS'],
				cicd: ['SFTP'],
			},
		},
		{
			id: 'web-inzicht',
			era: ERAS.earlyWeb,
			years: '2000–02',
			startYear: 2000,
			endYear: 2002,
			client: 'Web InZicht',
			role: 'Web Developer',
			type: 'employee',
			highlight: 'Where it all started.',
			tech: {
				frontend: ['JavaScript', 'HTML', 'CSS2', 'Flash'],
				backend: ['Classic ASP', 'MS Access'],
				cicd: ['FTP'],
			},
		},
	],
};

export function getTimeline(): TimelineData {
	return timeline;
}
