import type { TimelineData } from '@fg/shared';

/** The career timeline — real roles, employers and technologies from 2000 to today,
 *  grouped into era time-blocks, with side projects placed chronologically. Ported from
 *  the design prototype; tech names key into the shared TECH_REGISTRY for icons/colors. */
const timeline: TimelineData = {
	entries: [
		{
			id: 'portfolio',
			era: '2026 — Now',
			years: '2026',
			startYear: 2026,
			endYear: 'present',
			client: 'Portfolio Site',
			role: 'Full-Stack Engineer',
			type: 'independent',
			highlight: '3 frameworks, 1 site — you’re looking at it',
			tech: {
				frontend: ['React', 'Angular', 'Vue'],
				backend: ['Bun', 'Hono'],
				cicd: ['GitHub Actions', 'Docker'],
				ai: ['Claude Code', 'MCP'],
			},
		},
		{
			id: 'ai-healthcare',
			era: '2026 — Now',
			years: '2026',
			startYear: 2026,
			endYear: 2026,
			client: 'AI Healthcare Startup',
			role: 'Consulting Engineer',
			type: 'independent',
			tech: {
				frontend: ['React', 'SCSS Modules'],
				backend: ['Java', 'Spring Boot'],
				cicd: ['Docker'],
				ai: ['Claude Code'],
			},
		},
		{
			id: 'market-breadth',
			era: '2026 — Now',
			years: '2025–26',
			startYear: 2025,
			endYear: 2026,
			client: 'Market Breadth Dashboard',
			role: 'Full-Stack Engineer',
			type: 'independent',
			highlight: 'Real-time WebSocket market-data ingestion',
			tech: {
				frontend: ['React', 'Mantine UI', 'Vite', 'Recharts', 'Nx'],
				backend: ['NestJS', 'TimescaleDB', 'WebSockets'],
				cicd: ['Gitea Actions', 'Docker'],
				ai: ['Claude Code', 'OpenClaw', 'MCP'],
			},
		},
		{
			id: 'py-market-structure',
			era: '2026 — Now',
			years: '2025–26',
			startYear: 2025,
			endYear: 2026,
			client: 'py-market-structure',
			role: 'PyPI library',
			type: 'side-project',
			highlight: 'Published to PyPI with zero prior Python — built with Claude Code',
			tech: {
				backend: ['Python', 'PyPI'],
				cicd: ['GitHub Actions'],
				ai: ['Claude Code', 'MCP'],
			},
		},
		{
			id: 'amsterdam',
			era: '2020s — Netherlands (remote from Spain)',
			years: '2020–25',
			startYear: 2020,
			endYear: 2025,
			client: 'Gemeente Amsterdam',
			role: 'Lead Full-Stack Engineer — 5.5 years',
			type: 'independent',
			highlight: 'Led frontend across multiple teams; monorepo + feature-sliced architecture',
			tech: {
				frontend: ['React', 'Redux', 'TypeScript', 'Nx', 'GraphQL', 'Storybook'],
				backend: ['NestJS', 'Express', 'Azure', 'PostgreSQL', 'PostGIS'],
				cicd: ['GitLab CI', 'Azure Pipelines', 'GitHub Actions', 'Docker'],
				ai: ['Copilot', 'ChatGPT', 'ChatGPT API'],
			},
		},
		{
			id: 'trading-system',
			era: '2020s — Netherlands (remote from Spain)',
			years: '2018–now',
			startYear: 2018,
			endYear: 'present',
			client: 'Crypto Trading System',
			role: 'Parallel to employment',
			type: 'side-project',
			highlight: 'Runs alongside the day job — initiative, not a break from work',
			tech: {
				frontend: ['React', 'Next.js', 'Anychart'],
				backend: ['Node.js', 'PostgreSQL'],
				cicd: ['Bitbucket', 'Jenkins', 'Gitea Actions', 'Pulumi', 'k3s'],
				ai: ['ChatGPT API', 'Claude Code'],
			},
		},
		{
			id: 'tele2',
			era: 'Late 2010s — Netherlands',
			years: '2017–19',
			startYear: 2017,
			endYear: 2019,
			client: 'Tele2',
			role: 'Lead Full-Stack Engineer',
			type: 'employee',
			highlight: 'E-commerce SSR rebuild — 3× Lighthouse improvement',
			tech: {
				frontend: ['React', 'Redux', 'TypeScript/Flow', 'SSR', 'Webpack'],
				backend: ['Node.js', 'Express', 'PHP', 'Salesforce', 'MySQL'],
				cicd: ['Jenkins', 'Docker'],
			},
		},
		{
			id: 'deloitte-nl',
			era: 'Late 2010s — Netherlands',
			years: '2017',
			startYear: 2017,
			endYear: 2017,
			client: 'Deloitte Digital NL',
			role: 'Senior Frontend Engineer',
			type: 'employee',
			tech: {
				frontend: ['React', 'Redux', 'ES2016'],
				backend: ['AEM'],
			},
		},
		{
			id: 'deloitte-au-manager',
			era: '2013–2017 — Melbourne, Australia',
			years: '2016–17',
			startYear: 2016,
			endYear: 2017,
			client: 'Deloitte Digital AU',
			role: 'Frontend Lead (Manager)',
			type: 'employee',
			tech: {
				frontend: ['React', 'ES2016', 'Webpack'],
				backend: ['Sitecore', 'SQL Server'],
				cicd: ['Bamboo'],
			},
		},
		{
			id: 'deloitte-au-consultant',
			era: '2013–2017 — Melbourne, Australia',
			years: '2013–16',
			startYear: 2013,
			endYear: 2016,
			client: 'Deloitte Digital AU',
			role: 'Senior Frontend Engineer',
			type: 'employee',
			tech: {
				frontend: ['AngularJS', 'Backbone', 'jQuery', 'Highcharts', 'SCSS'],
				backend: ['Sitecore', 'SQL Server'],
				cicd: ['Bamboo'],
			},
		},
		{
			id: 'isobar',
			era: '2013–2017 — Melbourne, Australia',
			years: '2013',
			startYear: 2013,
			endYear: 2013,
			client: 'Visual Jazz Isobar',
			role: 'Frontend Developer',
			type: 'independent',
			tech: {
				frontend: ['AngularJS', 'RequireJS'],
				backend: ['PHP', 'AEM', 'MySQL'],
			},
		},
		{
			id: 'limelight',
			era: '2007–2013 — Brisbane, Australia',
			years: '2012–13',
			startYear: 2012,
			endYear: 2013,
			client: 'Limelight Digital',
			role: 'Full-Stack Developer',
			type: 'employee',
			tech: {
				frontend: ['jQuery', 'Backbone', 'Marionette', 'HTML5', 'CSS'],
				backend: ['PHP', 'MySQL', 'Kohana', 'Node.js'],
			},
		},
		{
			id: 'cru-digital',
			era: '2007–2013 — Brisbane, Australia',
			years: '2010–12',
			startYear: 2010,
			endYear: 2012,
			client: 'Cru Digital',
			role: 'Full-Stack Developer',
			type: 'employee',
			highlight: [
				'First single-page apps — hand-rolled in jQuery, a plugin per view — as responsive design took hold',
				'Early cloud — building CentOS AMI images from scratch on EC2',
			],
			tech: {
				frontend: ['jQuery'],
				backend: ['PHP', 'MySQL', 'SnappCMS', 'Magento'],
				cicd: ['Mercurial', 'Amazon EC2'],
			},
		},
		{
			id: 'ifactory',
			era: '2007–2013 — Brisbane, Australia',
			years: '2007–10',
			startYear: 2007,
			endYear: 2010,
			client: 'iFactory',
			role: 'Web Developer',
			type: 'employee',
			highlight: 'Lived through the Prototype.js → MooTools → jQuery era',
			tech: {
				frontend: ['Prototype.js', 'MooTools', 'jQuery', 'HTML5', 'CSS'],
				backend: ['PHP', 'MySQL', 'Joomla', 'Joomla 2', 'Magento', 'Seagull', 'PEAR'],
				cicd: ['SVN', 'rsync', 'Capistrano'],
			},
		},
		{
			id: 'cms-v2',
			era: '2007–2013 — Brisbane, Australia',
			years: '2008',
			startYear: 2008,
			endYear: 2009,
			client: 'Custom CMS v2',
			role: 'Seagull Framework',
			type: 'side-project',
			highlight: 'Built another CMS from scratch —  this time on the Seagull PHP framework',
			tech: {
				backend: ['PHP', 'MySQL'],
				cicd: ['Capistrano'],
			},
		},
		{
			id: 'hids',
			era: '2000–2006 — The Early Web (Netherlands)',
			years: '2005–06',
			startYear: 2005,
			endYear: 2006,
			client: 'HIDS',
			role: 'Web Developer',
			type: 'employee',
			tech: {
				frontend: ['JavaScript', 'AJAX'],
				backend: ['PHP', 'MySQL'],
				cicd: ['SFTP'],
			},
		},
		{
			id: 'cms-v1',
			era: '2000–2006 — The Early Web (Netherlands)',
			years: '2005',
			startYear: 2005,
			endYear: 2005,
			client: 'Custom CMS v1',
			role: 'Built from scratch',
			type: 'side-project',
			highlight: 'First CMS, hand-built',
			tech: {
				backend: ['PHP', 'MySQL'],
				cicd: ['SFTP'],
			},
		},
		{
			id: 'freelance-early',
			era: '2000–2006 — The Early Web (Netherlands)',
			years: '2003–04',
			startYear: 2003,
			endYear: 2004,
			client: 'Freelance',
			role: 'Web Developer',
			type: 'independent',
			tech: {
				frontend: ['JavaScript', 'XHTML / CSS'],
				backend: ['PHP'],
				cicd: ['SFTP'],
			},
		},
		{
			id: 'edf',
			era: '2000–2006 — The Early Web (Netherlands)',
			years: '2002–03',
			startYear: 2002,
			endYear: 2003,
			client: 'EDF',
			role: 'Web Developer',
			type: 'employee',
			tech: {
				frontend: ['JavaScript', 'XML/XSLT'],
				backend: ['Classic ASP', 'PHP', 'SQL Server'],
				cicd: ['SFTP'],
			},
		},
		{
			id: 'web-inzicht',
			era: '2000–2006 — The Early Web (Netherlands)',
			years: '2000–02',
			startYear: 2000,
			endYear: 2002,
			client: 'Web InZicht',
			role: 'Web Developer',
			type: 'employee',
			highlight: 'Where it all started.',
			tech: {
				frontend: ['JavaScript', 'HTML / CSS', 'Flash'],
				backend: ['Classic ASP', 'MS Access'],
				cicd: ['FTP'],
			},
		},
	],
	frameworks: [
		{ framework: 'jQuery', startYear: 2007, endYear: 2013, intensity: 'professional' },
		{ framework: 'Backbone', startYear: 2012, endYear: 2016, intensity: 'occasional' },
		{ framework: 'AngularJS', startYear: 2013, endYear: 2016, intensity: 'professional' },
		{ framework: 'React', startYear: 2016, endYear: 'present', intensity: 'professional' },
		{ framework: 'Angular', startYear: 2019, endYear: 2022, intensity: 'occasional' },
		{ framework: 'Vue', startYear: 2019, endYear: 2019, intensity: 'brief' },
		{ framework: 'Angular', startYear: 2025, endYear: 'present', intensity: 'professional' },
		{ framework: 'Vue', startYear: 2026, endYear: 'present', intensity: 'professional' },
	],
};

export function getTimeline(): TimelineData {
	return timeline;
}
