// Generates the timeline's tech-icon sprite + brand registry from the `simple-icons`
// package (official brand glyphs + colors), so the pills use real logos instead of
// hand-drawn approximations. Techs not in the set (or trademark-removed) fall back to a
// coloured text pill via BRAND_FALLBACK. Output: packages/shared/src/tech-icons.generated.ts
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import * as simpleIcons from 'simple-icons';

// tech name → simple-icons slug (null = no glyph, render a text pill)
const SLUGS: Record<string, string | null> = {
	// Frontend
	React: 'react',
	Angular: 'angular',
	Vue: 'vuedotjs',
	AngularJS: null,
	TypeScript: 'typescript',
	'TypeScript/Flow': 'typescript',
	Redux: 'redux',
	Webpack: 'webpack',
	Vite: 'vite',
	Storybook: 'storybook',
	Nx: 'nx',
	GraphQL: 'graphql',
	'Mantine UI': 'mantine',
	Recharts: null,
	Anychart: null,
	'Next.js': 'nextdotjs',
	jQuery: 'jquery',
	Backbone: 'backbonedotjs',
	Marionette: 'backbonedotjs',
	RequireJS: null,
	'Prototype.js': null,
	MooTools: null,
	Highcharts: 'highcharts',
	JavaScript: 'javascript',
	ES2016: 'javascript',
	SCSS: 'sass',
	'SCSS Modules': 'sass',
	SSR: null,
	Flash: null,
	'XML/XSLT': null,
	'HTML / CSS': 'html5',
	'XHTML / CSS': 'html5',
	AJAX: null,
	// Backend / DB
	Bun: 'bun',
	Hono: 'hono',
	'Node.js': 'nodedotjs',
	NestJS: 'nestjs',
	Express: 'express',
	Azure: 'microsoftazure',
	Java: 'openjdk',
	'Spring Boot': 'springboot',
	Salesforce: 'salesforce',
	AEM: null,
	Sitecore: null,
	PostgreSQL: 'postgresql',
	PostGIS: 'postgresql',
	MySQL: 'mysql',
	TimescaleDB: 'timescale',
	'SQL Server': 'microsoftsqlserver',
	'MS Access': null,
	WebSockets: 'socketdotio',
	PHP: 'php',
	'Classic ASP': null,
	Python: 'python',
	PyPI: 'pypi',
	// CI/CD & infra
	'GitHub Actions': 'githubactions',
	'GitLab CI': 'gitlab',
	'Azure Pipelines': 'azuredevops',
	'Gitea Actions': 'gitea',
	Docker: 'docker',
	Jenkins: 'jenkins',
	Bamboo: null,
	Bitbucket: 'bitbucket',
	Mercurial: 'mercurial',
	'Amazon EC2': 'amazonec2',
	SVN: 'subversion',
	'Visual SourceSafe': null,
	FTP: null,
	Pulumi: 'pulumi',
	k3s: 'k3s',
	// AI / LLM
	'Claude Code': 'claude',
	MCP: null,
	OpenClaw: null,
	Copilot: 'githubcopilot',
	ChatGPT: 'openai',
	'ChatGPT API': 'openai',
};

// brand colors for techs without a simple-icons glyph (keeps the pills on-brand).
const BRAND_FALLBACK: Record<string, string> = {
	AngularJS: '#b52e31',
	Recharts: '#8884d8',
	Anychart: '#e8623c',
	SSR: '#888888',
	Flash: '#cc0000',
	'XML/XSLT': '#e34c26',
	AJAX: '#888888',
	AEM: '#eb1000',
	Sitecore: '#eb1f1f',
	'MS Access': '#a4373a',
	'Classic ASP': '#cc2927',
	Azure: '#0078d4',
	'Azure Pipelines': '#0078d7',
	'Amazon EC2': '#ff9900',
	'SQL Server': '#cc2927',
	Salesforce: '#00a1e0',
	Marionette: '#888888',
	RequireJS: '#809cc9',
	'Prototype.js': '#888888',
	MooTools: '#888888',
	Bamboo: '#0052cc',
	'Visual SourceSafe': '#68217a',
	FTP: '#888888',
	MCP: '#d97706',
	OpenClaw: '#888888',
	ChatGPT: '#74aa9c',
	'ChatGPT API': '#74aa9c',
};

interface SimpleIcon {
	slug: string;
	hex: string;
	path: string;
}
const icons = simpleIcons as unknown as Record<string, SimpleIcon | undefined>;

function exportName(slug: string): string {
	return `si${slug[0].toUpperCase()}${slug.slice(1)}`;
}

const registry: Record<string, { brand: string; icon?: string }> = {};
const symbols = new Map<string, string>();

for (const [name, slug] of Object.entries(SLUGS)) {
	const icon = slug ? icons[exportName(slug)] : undefined;
	if (icon) {
		registry[name] = { brand: `#${icon.hex}`, icon: icon.slug };
		if (!symbols.has(icon.slug)) {
			symbols.set(
				icon.slug,
				`<symbol id="i-${icon.slug}" viewBox="0 0 24 24"><path fill="currentColor" d="${icon.path}"/></symbol>`,
			);
		}
	} else {
		registry[name] = { brand: BRAND_FALLBACK[name] ?? '#888888' };
	}
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">${[...symbols.values()].join('')}</svg>`;

const file = `// GENERATED by scripts/build-tech-icons.ts — do not edit by hand.
// Brand glyphs + colors sourced from the simple-icons package.
export const TECH_REGISTRY: Record<string, { brand: string; icon?: string }> = ${JSON.stringify(registry, null, '\t')};

export const TECH_SPRITE =
	${JSON.stringify(sprite)};
`;

await writeFile(
	resolve(import.meta.dirname, '../packages/shared/src/tech-icons.generated.ts'),
	file,
);
console.log(`✓ Built tech icons (${symbols.size} glyphs, ${Object.keys(registry).length} techs)`);
