// The custom-elements manifest is generated by `bun run cem` and is git-ignored, so it is absent
// when static type-checking runs without first building. This ambient declaration lets `preview.ts`
// import it without depending on the generated file; the manifest only feeds Storybook's control
// tables, so a structural type is unnecessary.
declare module '*custom-elements.json' {
	import type { Package } from 'custom-elements-manifest';
	const manifest: Package;
	export default manifest;
}
