import { setCustomElementsManifest } from '@storybook/web-components-vite';
import type { Preview } from '@storybook/web-components-vite';
import {
	applyFramework,
	applyTheme,
	sharedParameters,
	themeGlobalTypes,
} from '../../../.storybook/preview-shared';
// Generated by `bun run cem` (prestorybook hook). Drives the property/attribute/event tables
// and controls for the jb-* elements — there are no framework prop-types to introspect.
import manifest from '../custom-elements.json';

setCustomElementsManifest(manifest);

const preview: Preview = {
	parameters: sharedParameters,
	globalTypes: themeGlobalTypes,
	initialGlobals: { theme: 'light' },
	decorators: [
		(story, ctx) => {
			applyTheme(ctx.globals.theme);
			// Native elements show the neutral palette; framework sections supply their accent.
			applyFramework('neutral');
			return story();
		},
	],
};

export default preview;
